#!/bin/bash
# QUICK START - SISTEMA DE LOTES
# Sigue estos pasos para comenzar en 5 minutos

echo "==============================================="
echo "  QUICK START - SISTEMA DE LOTES"
echo "==============================================="
echo ""

# PASO 1: Verificar que PostgreSQL está corriendo
echo "PASO 1: Verificar PostgreSQL..."
echo "  [ ] ¿PostgreSQL está corriendo? (psql debe funcionar)"
echo "  Ejecuta en terminal: psql --version"
echo ""

# PASO 2: Crear la tabla
echo "PASO 2: Crear tabla LOTE en la BD..."
echo "  Opción A - Ejecutar todo el schema:"
echo "    psql -U usuario -d diana_inventario -f src/main/resources/schema.sql"
echo ""
echo "  Opción B - Ejecutar solo tabla lote:"
echo "    psql -U usuario -d diana_inventario"
echo "    \\i src/main/resources/LOTE_SETUP.sql"
echo ""

# PASO 3: Compilar
echo "PASO 3: Compilar el proyecto..."
echo "  mvn clean compile"
echo ""

# PASO 4: Ejecutar
echo "PASO 4: Ejecutar la aplicación..."
echo "  Desde IDE: Run Main class"
echo "  O desde terminal:"
echo "    mvn spring-boot:run"
echo "    (o tu comando específico de ejecución)"
echo ""

# PASO 5: Usar
echo "PASO 5: Usar el sistema de lotes..."
echo "  1. Abre la aplicación"
echo "  2. Ve a 'Cargar Datos'"
echo "  3. Selecciona 'Crear Lote'"
echo "  4. Completa el formulario"
echo "  5. Haz clic en 'Guardar'"
echo "  6. ¡Lote guardado! ✅"
echo ""

echo "==============================================="
echo "  VERIFICACIÓN RÁPIDA"
echo "==============================================="
echo ""

echo "¿La tabla se creó correctamente?"
echo "  psql -U usuario -d diana_inventario"
echo "  SELECT * FROM lote;"
echo ""

echo "¿El código compila?"
echo "  mvn clean compile -q"
echo "  (Sin errores = ✅)"
echo ""

echo "==============================================="
echo "  COMANDOS ÚTILES"
echo "==============================================="
echo ""
echo "Ver todos los lotes:"
echo "  SELECT * FROM lote ORDER BY fecha_creacion DESC;"
echo ""
echo "Ver lotes disponibles:"
echo "  SELECT * FROM lote WHERE estado = 'disponible';"
echo ""
echo "Ver estadísticas:"
echo "  SELECT COUNT(*) as total, AVG(peso_total) as peso_promedio FROM lote;"
echo ""
echo "Limpiar (CUIDADO - Borra todo):"
echo "  DELETE FROM lote;"
echo ""

echo "==============================================="
echo "  DOCUMENTACIÓN"
echo "==============================================="
echo ""
echo "Lee estos archivos para más información:"
echo "  - INSTRUCCIONES_LOTE.md"
echo "  - INTERFAZ_VISTA_PREVIA.md"
echo "  - SQL_CONSULTAS_LOTE.sql"
echo "  - CHECKLIST_VERIFICACION.md"
echo ""

echo "==============================================="
echo "  ¿PROBLEMAS?"
echo "==============================================="
echo ""
echo "Error: 'table lote does not exist'"
echo "  → Ejecuta: psql -f src/main/resources/schema.sql"
echo ""
echo "Error: 'Cannot resolve method crearLoteConAutorizacion'"
echo "  → Limpia caché: mvn clean"
echo "  → Recompila: mvn compile"
echo ""
echo "Error: NullPointerException"
echo "  → Verifica que BD está corriendo"
echo "  → Verifica que app_usuario existe"
echo ""
echo "Error: Dialog no se abre"
echo "  → Verifica que CrearLoteDialog.java existe"
echo "  → Verifica que CargarDatos.java tiene los listeners"
echo ""

echo "==============================================="
echo "  ¡LISTO!"
echo "==============================================="
echo ""
echo "Sigue los 5 pasos de arriba y el sistema"
echo "de lotes debería funcionar correctamente."
echo ""
echo "¿Necesitas ayuda? Consulta:"
echo "  - RESUMEN_FINAL_COMPLETO.md"
echo "  - CHECKLIST_VERIFICACION.md"
echo ""

